version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rightel_financial
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: financial-management-app
    container_name: financial-management-app
    ports:
      - "8082:8082"
    volumes:
      - /path/to/config:/config
    depends_on:
      - postgres

volumes:
  postgres_data:
